
media: media

content:
  - name: products
    label: محصولات سبزکود
    type: collection
    path: products
    format: json
    filename: "{primary}.json"
    fields:
      - name: name
        label: نام محصول
        type: string
        required: true
      - name: price
        label: قیمت
        type: string
      - name: description
        label: توضیحات
        type: text
      - name: image
        label: تصویر محصول
        type: string
        